spring:
  config:
    import: optional:configserver:http://configUser:configPassword@localhost:8081
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://discUser:discPassword@localhost:8761/eureka/

